### ISSUE TITLE
The `unfly` command does nothing

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#145]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

The `unfly` command in the test place does not actually unfly the target player.

Note: Both the `fly` and `unfly` command print `An error occurred while running this command. Check the console for more information.`, but the `fly` command appears to work as intended.

### How can we reproduce this bug?

1. Enter the test place
2. Enter `fly me` in the F2 console (or chat `/fly me`)
3. Enter `unfly me` in the F2 console (or chat `/unfly me`)
4. Observe still being able to fly

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/61dcb66c-fbb8-4f99-abbb-16bb40c00e0b

this bug has been resolved (as seen in the video above) due to the recent update to both the fly and unfly command.

this bug, however, is still relevant to the staging version of the game due to this update not being pushed to staging yet.
