### ISSUE TITLE
Cooler does not show up in Unstable/Staging MBTools

### ISSUE THREAD

**Issue by suley135** [Eggs-D-Studios/wos-issues#186]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

When searching for the Cooler in Studio using the MBTools (unstable/staging) plugin, it does not show up and is unable to be used.

### How can we reproduce this bug?

Open the MBTools (unstable/staging) plugin in studio, search for cooler, it will not show there is a cooler in the model compiler.

### Frequency

Always

**Comment by dogranger1** [comment]
![image](https://github.com/user-attachments/assets/8832a5e2-89f2-4446-8990-ae668d4ae0fb)

this bug is valid, though the unstable version of MBTools is basically pointless since all the features get directly pushed to stable now.

the stable version of MBTools is also missing quite a few parts, like WaterCooler s and Solenoid s.
