### ISSUE TITLE
MBTools emparting part shift into models when compiled.

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#217]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When I compiled my factory some of the parts got random ~0.001 rotation and position offsets.
This error was visible in game and on my studio model after compiling it.

### How can we reproduce this bug?

1. Verify your parts in studio have the correct non-shifted positions
2. Select all parts
3. Click compile
4. Check the positions of your parts in studio, they will now be slightly offset
And as an extra note, loading that model in-game it will have the same part shift.

### Frequency

Always

**Comment by Hexcede** [comment]
@1-creare-1 The model builder does not modify parts that are being compiled at all, produce any welds, etc so if you see shift on the actual raw model you compiled from it wasn't caused by the model builder.

If you're referring to just the compiled output and not the parts inside of your model, saving is not completely lossless because of the offset computations, there is a tiny amount of floating point error. You can try moving your model closer to the world origin in Studio and that should help to resolve the problem. As of the last update this error also no longer accumulates and all offset/location data is preserved losslessly across saves.
