### ISSUE TITLE
furnaces are being very stubborn for me

### ISSUE THREAD

**Issue by hellobot2001** [Eggs-D-Studios/wos-issues#255]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

there are 3 main problems for me. first, sometimes when trying to craft a furnace, it didn't craft for a long time (sometimes didn't even craft at all). I've noticed this less today, however. the second problem is that the furnaces are incredibly stubborn, and simply refuse to send heat to my boilers, preferring to send heat to everything else surrounding it, with the surroundings reaching millions of degrees Fahrenheit, while the boilers remain only 66, and one time it went all the way to -400 Fahrenheit. third, the furnace doesn't care about locked parts. I've accidentally bumped into one with my spaceship and lost a few solar panels (everything was locked)

### How can we reproduce this bug?

first problem:
1. try crafting a furnace (only seems to happen sometimes, I don't know what causes it)

second problem:
1. attach furnace to boiler
2. give furnace something flammable

third problem:
1. have a furnace
2. make any locked flammable part touch it

### Frequency

Most of the time

**Comment by madgarry105** [comment]
😃

**Comment by xortxa** [comment]
wdym by "give furnace" on 2nd problem

**Comment by hellobot2001** [comment]
my brain went too fast

**Comment by Hexcede** [comment]
Most of these things aren't bugs it's just weird behaviour/lag. Fairly soon the `Boiler` isn't going to require any heat at all and instead will require `Coal` again, it wasn't supposed to still have the 100 C heat requirement for the update.

**Comment by dogranger1** [comment]
bug numero one is probably related to the ping of the server (likely due to Furnace s not being optimised (though i could be wrong))

bug numero two:


https://github.com/user-attachments/assets/24178ea9-7cd0-4aec-a257-bf7c2c7f8771

(probably fixed)

bug numero three:

https://github.com/user-attachments/assets/b04a9512-837d-4848-9c25-bb0e76f7e90c

(fixed)

i'm pretty sure that the entire heat system needs a re-work due to some other heat - related bugs (like how heat can only travel though a certain amount of parts before it stops).
