### ISSUE TITLE
Placed Spawn/Cloning Bay at planet and it still doesn't show on spawnlist

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#320]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I placed a Spawnpoint and Cloning Bay at a planet and went into a Teleporter. The teleporter took me to space so I kept dying but the respawn menu did not prompt the area with a Spawn and Cloning Bay. Ironically it prompted an area in the middle of nowhere space that had NO SPAWN/CLONING bay which made no sense.
![image](https://github.com/user-attachments/assets/57a323d6-94b5-47a9-b00f-5fa4c08dd32d)

### How can we reproduce this bug?

1. Go to any planet
2. Place spawnpoint and cloning bay
3. Exit the planet
4. Reset
5. It doesnt show in your spawnlist

### Frequency

Always

**Comment by riptidemamba** [comment]
I would include a clip of it happening but it has my coords and I do not want to leak it

**Comment by Hexcede** [comment]
I can't reproduce the issue but if someone can come up with a consistent repro that works for me that would be awesome.

**Comment by madgarry105** [comment]
wants help help help

**Comment by dogranger1** [comment]
![image](https://github.com/user-attachments/assets/ae0c4d11-2d7b-4c84-b574-8f2a87dc8bee)

(image of the CloningBay at the region where the Cloningbay is)

![image](https://github.com/user-attachments/assets/50f6e495-7518-4617-a2cc-c2f9d4e020ce)

(image of the CloningBay at an empty region)

im pretty sure that this got fixed after the bug where servers did not save after you left them got fixed, since i haven't encountered this bug since the latter bug got fixed.

note: there may be a bug where CloningBay s do not register that they are powered.
