### ISSUE TITLE
certain resource parts spawn with dimensions 1x2x4.9 instead of 1x2x4

### ISSUE THREAD

**Issue by NobodyImportant64** [Eggs-D-Studios/wos-issues#43]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When spawning resources that would usually be 4 studs long through the crafting menu from containers they spawn with an extra 0.9 studs of length. This effect does not appear to happen when resources are spawned using the pickaxe by mining them.

### How can we reproduce this bug?

1) Open the crafting menu and spawn a resource like gold, iron, or copper that is usually a 1x2x4 brick.

### Frequency

Always

**Comment by Hexcede** [comment]
> When spawning resources that would usually be 4 studs long through the crafting menu from containers they spawn with an extra 0.9 studs of length. This effect does not appear to happen when resources are spawned using the pickaxe by mining them.

This isn't a bug. `Copper`, `Iron`, and `Wood` all do not have this. It is only `Gold`, which does also spawn in large when mined with the pickaxe tool. This is because the default size of `Gold` is not 1x2x4.

Some of the resources listed (copper & iron) do not have this issue. This is because e.g. `Gold` legitimately just has this as its default size for some reason. The hammer tool
