### ISSUE TITLE
`DevBattery` can only have power extracted if the resource request type matches exactly

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#504]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

A Sorter set to move Any will not move Power. The expected behaviour would be for the Sorter to move Power.

The `Any` rule for Sorters should match Power since it does match Power for Filters.

### How can we reproduce this bug?

1. Load this model: [Power Sorter Repro.json](https://github.com/user-attachments/files/17467667/Power.Sorter.Repro.json)
2. Observe the leftmost/topmost PowerCell remaining empty.

Note that the Filter is set to `Any`, meaning that `Any` *does* match Power.
![image](https://github.com/user-attachments/assets/7312c057-ac2f-42b8-9556-fbedc211ad85)

### Frequency

Always

**Comment by Hexcede** [comment]
The bug is actually slightly different than you described but I was able to identify the problem. The `DevBattery` spawns with a pre-set amount of power but one of the values the game uses to keep track of container states is never set.

The codepath that checks type refinements like `Any` relies on the unset value to be set, so it fails to find `Power` to move out of the `DevBattery` until you push power into the `DevBattery` at least once.

I'm about to push the fix.
