### ISSUE TITLE
Switch-type parts not affected by antenna-triggered FlipFlop polysilicon when antenna is connected to them

### ISSUE THREAD

**Issue by lilp123a** [Eggs-D-Studios/wos-issues#522]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Switch-type parts (Switch, Valve, HeatValve, Hatch) are not affected by FlipFlop polysilicon triggered via antenna if said antenna is simultaneously connected to the Switch-type part in question.

### How can we reproduce this bug?

1. Spawn 2 antennae, a button, a switch(-type) part, and a polysilicon
2. Set the polysilicon to FlipFlop and connect it to the switch
3. Place one antenna so that it is connected to both the switch and the polysilicon
4. Connect the button to the second antenna
5. Activating the button will have no effect on the polysilicon. If the antenna is then moved to only be connected to the polysilicon, activating the button will now toggle the switch as expected.

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/1b4b5c8f-8706-439c-a198-e84284755344

This fundamentally occurs because the polysilicon signal can travel through TriggerWire s and Antenna s, which means that when the button is clicked the polysilicon sends a triggersignal back through the antenna but this time the triggersignal is a polysilicon triggersignal (which means that it would change the state of parts). Simply put, a second feedback triggersignal is sent through the antenna which changes the state of the switch twice.
