### ISSUE TITLE
Part.CFrame returns Userdata

### ISSUE THREAD

**Issue by minimic2002** [Eggs-D-Studios/wos-issues#539]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Literally try doing maths with it, everything errors

### How can we reproduce this bug?

print(type(GetPart("Gyro").CFrame))

### Frequency

Always

**Comment by Hexcede** [comment]
@minimic2002 All `CFrame`s are userdatas. `type(CFrame.identity)` returns `userdata`:
![image](https://github.com/user-attachments/assets/22110cfd-47b6-4d58-9127-7e7b439fe7c7)

Additionally, the game does not sandbox CFrames at all because there'd be no reason to. They are provided to your code as-is.
