### ISSUE TITLE
Gyro Min And Max are non functional

### ISSUE THREAD

**Issue by minimic2002** [Eggs-D-Studios/wos-issues#540]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I was testing a rangefinder, and expect the gyro to only look when its within the min and max as usual, it aims straight away and will also constantly trigger

### How can we reproduce this bug?

radar something

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/4874e87c-6ad5-439d-ba45-23d7e6729854


Perhaps you might have left a space between "min" and the number. It works as intended, despite that it will point at the object despite it being outside the desired (but I believe this to happen due to lag, as the gyro will discontinue updating its orientation and stop triggering a little while after this).
