### ISSUE TITLE
Model loaded buttons / buttons created with the old MBTools are not usable

### ISSUE THREAD

**Issue by 0mori1** [Eggs-D-Studios/wos-issues#67]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

I load in the puter, try to press the power button, uh oh! the button does not function

### How can we reproduce this bug?

load in a button / load in a button made using the old mbtools

### Frequency

Always

**Comment by Hexcede** [comment]
This is not actually a bug, this is more of a UX issue. You need to add the `ClickButton` or `KeyButton` components to the `Button` instance because the behaviour is no longer part of the button part itself but rather the button part just comes with the components already there.

To create components with the unstable model builder you just need to create a `Configuration` instance inside of the part named after the component (e.g. `ClickButton`). You can then place value instances inside it like you normally would when configuring it if you need to configure it.
