### ISSUE TITLE
single player creative

### ISSUE THREAD

**Issue by badname64** [Eggs-D-Studios/wos-issues#69]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Stable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

allows us to add weapons in our creative worlds and have certain people go in it

### What do you propose? What should change, or what should be added?

frens can join and you can kick n ban em or a join code added to it for others and it allows weapons and bombs there and so no one can greif or piss you off

**Comment by Hexcede** [comment]
This is currently something that isn't going to be worked on because it would cause too much fragmentation in the playerbase without addressing the real underlying problems (e.g. abuse in the test zone). I'd prefer to fix the things that make private test zone areas desirable over implementing private test zones that will end up making public test zones effectively pointless.
